### ISSUE TITLE
Build generates undefined error on dependency for notify

### ISSUE THREAD

**Issue by nryberg** [depado/smallblog#4]
When I try to build smallblog, I get the following:

`go get -u github.com/Depado/smallblog`
`# github.com/Depado/smallblog/filesystem`
`go/src/github.com/Depado/smallblog/filesystem/filesystem.go:21: undefined: notify.InMovedTo`
`go/src/github.com/Depado/smallblog/filesystem/filesystem.go:21: undefined: notify.InMovedFrom`
`go/src/github.com/Depado/smallblog/filesystem/filesystem.go:30: undefined: notify.InMovedTo`
`go/src/github.com/Depado/smallblog/filesystem/filesystem.go:42: undefined: notify.InMovedFrom`

**Comment by Depado** [comment]
Hello !

I just tried downloading and installing smallblog from scratch in a brand new `GOPATH` and didn't face any issue. What's your operating system ?

**Comment by nryberg** [comment]
Hi!   

Yeah - it builds fine in Ubuntu/Linux, and hangs on a Mac.  Not sure what the problem is.

go get -u github.com/rjeczalik/notify   

builds just fine, and I think that’s what you’re depending on that throws the error on my machine.   

--  
Nick R

**Comment by Depado** [comment]
I think that's because notify uses conditional builds, since the filesystem is different depending on your OS. Smallblog wasn't intended to work on a Mac system for example. 

Unfortunately I don't have a Mac to test this on. But I would have to split `filesystem.go` in two separate files `filesystem_linux.go` and `filesystem_darwin.go`

If you have some time and like to contribute, a PR would be welcome ! Otherwise I'll do it when I'll have the time to test it out (borrowing a mac haha)
